Repository Netcracker/qubership-env-checker, pull requests merged in 2025-09, with the labels that each got.

#53 fix(ci): fix for link-checker workflow
  .github/workflows/link-checker.yaml
Labels: bug

#63 fix: update kubectl version
  Dockerfile
  README.md
Labels: bug

#70 feat: Add notebook orchestrator
  Dockerfile
  charts/env-checker/templates/CloudPassportSecret.yaml
  charts/env-checker/templates/_templates.yaml
  charts/env-checker/values.yaml
  jovyan/run.sh
  jovyan/shells/namespace_validator.sh
  jovyan/shells/remove_out_catalogs.sh
  jovyan/shells/set_paths.sh
  jovyan/utils/env_checker_utils.py
  jovyan/utils/infra/s3.py
  jovyan/utils/json_report_generator.py
  jovyan/utils/json_schema_validation.py
  jovyan/utils/monitoringUtils.py
  jovyan/utils/nb_data_manipulation_utils.py
  jovyan/utils/parseOut.py
  jovyan/utils/report_generator.py
Labels: bug, enhancement

#72 fix: fix cloud passport secret manifest
  charts/env-checker/templates/CloudPassportSecret.yaml
Labels: bug

#77 fix: upgrade yq and nodejs versions
  Dockerfile
Labels: bug

#73 fix: Clean dockerfile
  Dockerfile
  charts/env-checker/templates/Deployment.yaml
  charts/env-checker/values.yaml
  docs/tests/TestGuide.md
  docs/tests/images/unit_test_run_html_example.jpg
  installation/python/docker_healthcheck.py
  installation/shells/start-notebook.sh
  installation/shells/start-singleuser.sh
  jovyan/run.sh
  jovyan/tests/CompositeUnitTestNotebook.ipynb
  jovyan/tests/__init__.py
  jovyan/tests/composite_test.yaml
  jovyan/tests/notebooks/test_notebook.ipynb
  jovyan/tests/test_utils/__init__.py
  jovyan/tests/test_utils/json_parsing.py
  jovyan/tests/unittests/integrations/git_integration_test.py
  jovyan/tests/unittests/integrations/s3_integration_test.py
  jovyan/tests/unittests/reports/html_creation_test.py
  jovyan/tests/unittests/reports/pdf_creation_test.py
  jovyan/tests/unittests/reports/pdf_disabling_test.py
  jovyan/tests/unittests/shells/bulk_call_test.py
  jovyan/tests/unittests/shells/j_flag_test.py
  jovyan/tests/unittests/shells/o_flag_test.py
  jovyan/tests/unittests/shells/y_flag_test.py
  jovyan/utils/custom_reporter.py
Labels: bug, documentation, enhancement

#80 feat: adding IDE capabilities
  Dockerfile
Labels: bug
